on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: octoDNS Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@master
        with:
          python-version: '3.9'

      - uses: py-actions/py-dependency-install@v2

      - run: octodns-sync --config-file=./config.yaml --doit
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}